package com.portal.constants;

public enum AllowedRmsMasters {
	
	GDRMSADSTYPE("Rms Ads Type"),GDRMSDISCOUNTTYPES("Rms Discount Type"),GDRMSEDITIONTYPE("Rms Edition Type"),GDRMSFIXEDFORMATS("Rms Fixed Format")
	,GDRMSFORMATTYPES("Rms Format Type"),GDRMSGENERATEDBYOTHERS("Rms Generated By"),GDRMSMULTIDISCOUNT("Rms MultiDiscount"),GDRMSPAGEPOSITIONS("Rms Page Positions"),
	GDRMSSCHEMES("Rms Schemes"),GDCLASSIFIEDGROUP("Classified Group"),GDCLASSIFIEDSUBGROUP("Classified Sub Group"),GDCLASSIFIEDCHILDGROUP("Classified Child Group");
	
	public final String master;
	
	private AllowedRmsMasters(String master) {
		this.master = master;
	}
	
	public String getValue() {
		return master;
	}
	

}
